### ISSUE TITLE
I don't get all objects in the resoursekind, so I got the error failureMessage: Not a UUID  at data-push.py

### ISSUE THREAD

**Issue by Vidanez** [sajaldebnath/vrops-data-push#1]
python data-push.py 
{"property-content": [{"statKey": "Summary|creationDate", "timestamps": [1518540098777], "values": ["01/29/18"]},{"statKey": "Summary|inside-vm-Hostname", "timestamps": [1518540098777], "values": ["mpc-nbrest-02.msorange.dom" ]}]}
Traceback (most recent call last):
  File "data-push.py", line 90, in <module>
    vrops.add_properties( proReq,id=resourceid)
  File "/Users/jvidanez/Workspace/pyenvs/py27/lib/python2.7/site-packages/nagini-1.0-py2.7.egg/nagini/nagini.py", line 285, in <lambda>
    new_method = lambda self, *args, **kwargs: self._rest_request(rest_method, params=kwargs, content=args)
  File "/Users/jvidanez/Workspace/pyenvs/py27/lib/python2.7/site-packages/nagini-1.0-py2.7.egg/nagini/nagini.py", line 215, in _rest_request
    return self.do_request(templated_url, client_method, encoded_params, data, binary, files)
  File "/Users/jvidanez/Workspace/pyenvs/py27/lib/python2.7/site-packages/nagini-1.0-py2.7.egg/nagini/nagini.py", line 253, in do_request
    raise e
nagini.nagini.ClientSideException: Http error code = 400
Reason = 400. Error object = {u'apiErrorCode': 400,
 u'httpStatusCode': 400,
 u'message': u'Cannot convert "None" to uuid',
 u'moreInformation': [{u'name': u'api-uri',
                       u'value': u'/suite-api/api/resources/None/properties'}],
 u'validationFailures': [{u'failureMessage': u'Not a UUID',
                          u'violationPath': u'resourceId'}]}

**Comment by Vidanez** [comment]
I found that this function is not returning all objects, and that the issue:
def match_resources(resourceknd,adapter):

**Comment by Vidanez** [comment]
maybe def match_resources(resourceknd,adapter) is returning the full list but the mapping is not filtering it fine

resourcemapping = match_resources(resourceknd, adapter)
print(resourcemapping)

**Comment by Vidanez** [comment]
I have keept searching and I found the root of the issue. 
I'm not getting all "virtual Machine" objects. I have removed the comment in the "print(resourcemapping)" and I count the output and I got 946 objects but I can see at the inventory explorer that I have around 3000. 
Buffer limitation on the client or server side, looks like the root issue

**Comment by Vidanez** [comment]
OK I found the issue and the solution and I'm closing this because is not related with your code but with the Nagini library itself. 
By default the system answer with 1000 object per page as we can see at 
https://<vrops-server>/suite-api/api/adapterkinds/VMWARE/resourcekinds/VIRTUALMACHINE/resources
In order to get more objects in the same page you need to pass the maximum number of objects that you want like
https://<vrops-server>/suite-api/api/adapterkinds/VMWARE/resourcekinds/VIRTUALMACHINE/resources/resources/?page=0&pageSize=4000

So as we are using this by Nagini client we need to translate this to Nagini.
Having a look on the Nagini code at the function that we call 
find_create_resource_with_adapter_uuid or find_create_resource_with_adapter_key, Nagini use a method called get_resources_with_adapter_and_resource_kind, but in the admitted parameters there is not PageSize
But if we go to the method.json we can see that the option is there 
  "name" : "get_resources_with_adapter_and_resource_kind",
    "url" : "/api/adapterkinds/{adapterKindKey}/resourcekinds/{resourceKindKey}/resources",
    "http_method" : "GET",
    "doc" : "Query for Resources within a particular Adapter Kind and Resource Kind.<br/>",
    "query_params" : [ {
      "name" : "page",
      "doc" : "Page number from which data needs to be displayed (0-based)",
      "type" : "int",
      "optional" : true,
      "repeating" : false
    }, {
      "name" : "pageSize",
      "doc" : "Expected number of entries per page",
      "type" : "int",
      "optional" : true,
      "repeating" : false },

So I have modify nagini.py on the both function I commented aboce to introduce the PageSize as a parameter and Magic ... it works !!!
